env: 'production'

app:
  name: 'student-management'
  version: '1.0.0'

http_server:
  port: ':8080'
  read_timeout: 10

log:
  log_level: 'debug'

mysql_config:
  db_username: 'root'
  db_password: 'Admin@123'
  db_host: 'localhost'
  db_database: 'student_management'
  db_port: 3306

